### ISSUE TITLE
Make VariableList iterable

### ISSUE THREAD

**Issue by evsiretanu** [tim-coutinho/occam#10]
`VariableList` is not currently iterable, meaning that loops like `for v in variable_list` will not work. Need to implement an iterator in `pyoccam.cpp` to enable this functionality

**Comment by tim-coutinho** [comment]
Do you need this implemented on the C++ side? If you could do it on just the Python side, you just need to define the following in the Python class:
```python
def __iter__(self):
    for variable in self.variable_list:
        yield variable
```
assuming you have access to a list of variables in the class. This will let you instantiate a VariableList python object and iterate over the object directly.

**Comment by evsiretanu** [comment]
Yes, this needs to be implemented on C++ side, as python will not know how to iterate over that list. When the reference to `VariableList` is returned, python only knows that it's an object but does not know anything about it's underlying functionality or representation, which is located in C++.
